/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	camelv1alpha1 "github.com/camel-tooling/camel-dashboard-operator/pkg/apis/camel/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// CamelMonitorStatusApplyConfiguration represents a declarative configuration of the CamelMonitorStatus type for use
// with apply.
//
// CamelMonitorStatus defines the observed state of an App.
type CamelMonitorStatusApplyConfiguration struct {
	// the actual phase
	Phase *camelv1alpha1.CamelMonitorPhase `json:"phase,omitempty"`
	// the image used to run the application
	Image *string `json:"image,omitempty"`
	// Some information about the pods backing the application
	Pods []PodInfoApplyConfiguration `json:"pods,omitempty"`
	// The number of replicas (pods running)
	Replicas *int32 `json:"replicas,omitempty"`
	// A resume of the main App parameters
	Info *string `json:"info,omitempty"`
	// The percentage of success rate
	SuccessRate *SLIExchangeSuccessRateApplyConfiguration `json:"sliExchangeSuccessRate,omitempty"`
	// The conditions catching more detailed information
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// CamelMonitorStatusApplyConfiguration constructs a declarative configuration of the CamelMonitorStatus type for use with
// apply.
func CamelMonitorStatus() *CamelMonitorStatusApplyConfiguration {
	return &CamelMonitorStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *CamelMonitorStatusApplyConfiguration) WithPhase(value camelv1alpha1.CamelMonitorPhase) *CamelMonitorStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *CamelMonitorStatusApplyConfiguration) WithImage(value string) *CamelMonitorStatusApplyConfiguration {
	b.Image = &value
	return b
}

// WithPods adds the given value to the Pods field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Pods field.
func (b *CamelMonitorStatusApplyConfiguration) WithPods(values ...*PodInfoApplyConfiguration) *CamelMonitorStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPods")
		}
		b.Pods = append(b.Pods, *values[i])
	}
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *CamelMonitorStatusApplyConfiguration) WithReplicas(value int32) *CamelMonitorStatusApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithInfo sets the Info field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Info field is set to the value of the last call.
func (b *CamelMonitorStatusApplyConfiguration) WithInfo(value string) *CamelMonitorStatusApplyConfiguration {
	b.Info = &value
	return b
}

// WithSuccessRate sets the SuccessRate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SuccessRate field is set to the value of the last call.
func (b *CamelMonitorStatusApplyConfiguration) WithSuccessRate(value *SLIExchangeSuccessRateApplyConfiguration) *CamelMonitorStatusApplyConfiguration {
	b.SuccessRate = value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *CamelMonitorStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *CamelMonitorStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
