apiVersion: v1
entries:
  camel-monitor:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2025-08-18T10:09:31.583941002+02:00"
    description: Monitor your fleet of Camel applications on Kubernetes
    digest: 6a2d7b05be1618033022948a4b573fe2b4938cd48ae70c5492acdb03e355d629
    home: https://camel.apache.org/camel/latest/
    icon: https://github.com/apache/camel/raw/main/docs/img/logo64-d.png
    keywords:
    - integration
    - camel
    - dashboard
    maintainers:
    - email: pcongiusti@apache.org
      name: pcongiusti
    name: camel-monitor
    sources:
    - https://github.com/camel-tooling/camel-monitor-operator
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard-charts/camel-monitor-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 0.0.2-SNAPSHOT
    created: "2025-08-13T10:02:54.868688893+02:00"
    description: Monitor your fleet of Camel applications on Kubernetes
    digest: 926b0fe49c51e68b79caf5c73b612d41985488538d68f706ade94b2c3dd028fd
    home: https://camel.apache.org/camel/latest/
    icon: https://github.com/apache/camel/raw/main/docs/img/logo64-d.png
    keywords:
    - integration
    - camel
    - dashboard
    maintainers:
    - email: pcongiusti@apache.org
      name: pcongiusti
    name: camel-monitor
    sources:
    - https://github.com/camel-tooling/camel-monitor-operator
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard-charts/camel-monitor-0.0.2-SNAPSHOT.tgz
    version: 0.0.2-SNAPSHOT
  - apiVersion: v2
    appVersion: 0.0.1-SNAPSHOT
    created: "2025-07-29T11:05:26.204498856+02:00"
    description: Monitor your fleet of Camel applications on Kubernetes
    digest: 4620c8e93c5233305c661333419d4a05206c5faf03ba0fd76e048fc2cf4351f1
    home: https://camel.apache.org/camel/latest/
    icon: https://github.com/apache/camel/raw/main/docs/img/logo64-d.png
    keywords:
    - integration
    - camel
    - dashboard
    maintainers:
    - email: pcongiusti@apache.org
      name: pcongiusti
    name: camel-monitor
    sources:
    - https://github.com/camel-tooling/camel-monitor-operator
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard-charts/camel-monitor-0.0.1.tgz
    version: 0.0.1
  - apiVersion: v2
    appVersion: 0.0.1-SNAPSHOT
    created: "2025-06-26T11:00:14.331460212+02:00"
    description: Monitor your fleet of Camel applications on Kubernetes
    digest: 0f8362b1300a3de671016a66d3f80ac9ecf0c26bad565e482b7235b4bab3ec96
    home: https://camel.apache.org/camel/latest/
    icon: https://github.com/apache/camel/raw/main/docs/img/logo64-d.png
    keywords:
    - integration
    - camel
    - dashboard
    maintainers:
    - email: pcongiusti@apache.org
      name: pcongiusti
    name: camel-monitor
    sources:
    - https://github.com/camel-tooling/camel-monitor-operator
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard-charts/camel-monitor-0.0.1-SNAPSHOT.tgz
    version: 0.0.1-SNAPSHOT
  camel-monitor-operator:
  - annotations:
      charts.openshift.io/name: Camel Monitor Operator
    apiVersion: v2
    appVersion: 0.0.2
    created: "2026-05-12T10:12:41.916817838+02:00"
    description: A Helm chart for installing the Camel Monitor Operator
    digest: 0d9ca405f236d1ba18c6b108257bcbf5dc45806a5dcf1f182b90677228cd006e
    home: https://camel-tooling.github.io/camel-dashboard/
    icon: https://github.com/camel-tooling/camel-dashboard/raw/main/docs/static/images/logo.png
    keywords:
    - integration
    - camel
    - monitor
    - dashboard
    kubeVersion: '>= 1.33'
    maintainers:
    - email: pcongiusti@apache.org
      name: pcongiusti
    name: camel-monitor-operator
    sources:
    - https://github.com/camel-tooling/camel-monitor-operator
    type: application
    urls:
    - https://camel-tooling.github.io/camel-dashboard/charts/camel-monitor-operator-0.0.2.tgz
    version: 0.0.2
generated: "2026-05-12T10:12:41.916058929+02:00"
