/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/camel-tooling/camel-dashboard-operator/pkg/apis/camel/v1alpha1"
	camelv1alpha1 "github.com/camel-tooling/camel-dashboard-operator/pkg/client/camel/applyconfiguration/camel/v1alpha1"
	internal "github.com/camel-tooling/camel-dashboard-operator/pkg/client/camel/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=camel.apache.org, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("CamelMonitor"):
		return &camelv1alpha1.CamelMonitorApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("CamelMonitorStatus"):
		return &camelv1alpha1.CamelMonitorStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ExchangeInfo"):
		return &camelv1alpha1.ExchangeInfoApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObservabilityServiceInfo"):
		return &camelv1alpha1.ObservabilityServiceInfoApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PodInfo"):
		return &camelv1alpha1.PodInfoApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RuntimeInfo"):
		return &camelv1alpha1.RuntimeInfoApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SLIExchangeSuccessRate"):
		return &camelv1alpha1.SLIExchangeSuccessRateApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
