# ---------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------

name: e2e

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request:
    branches:
      - main
      - "release-*"
    paths-ignore:
      - 'docs/**'
      - 'proposals/**'
      - '**.adoc'
      - '**.md'
      - 'KEYS'
      - 'LICENSE'
      - 'NOTICE'
  push:
    branches:
      - main
      - "release-*"
    paths-ignore:
      - 'docs/**'
      - 'proposals/**'
      - '**.adoc'
      - '**.md'
      - 'KEYS'
      - 'LICENSE'
      - 'NOTICE'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        submodules: recursive

    - name: Infra setting
      uses: ./.github/actions/infra-setting

    - name: Install Camel Monitor operator
      shell: bash
      run: |
        kubectl create ns camel
        make install-k8s-global
        kubectl wait --for=condition=available deployment/camel-monitor-operator --timeout=180s -n camel

    # Very useful to create testing application on the fly
    - name: Install Camel K operator
      shell: bash
      run: |
        kubectl create ns camel-k
        kubectl apply -k github.com/apache/camel-k/install/overlays/kubernetes/descoped?ref=v2.9.1 --server-side
        kubectl wait --for=condition=available deployment/camel-k-operator --timeout=180s -n camel-k
        REGISTRY=$(kubectl -n kube-system get service registry -o jsonpath='{.spec.clusterIP}')
        sed -i "s/REPLACETHIS/$REGISTRY/g" ./.github/actions/infra-setting/default-itp.yaml
        kubectl apply -f ./.github/actions/infra-setting/default-itp.yaml
        kubectl wait --for=jsonpath='{.status.phase}'=Ready itp/camel-k -n camel-k --timeout=120s
        kubectl get itp -n camel-k

    - name: Run test
      shell: bash
      run: |
        GOTESTFMT="-json 2>&1 | gotestfmt" make test-common
